#
# This Docker Compose file will create a complete system to run this demo.
#
# To build from source:
#   export PRAVEGA_HOST_IP=your_host_ip
#   ./gradlew gateway:distTar && docker-compose build && docker-compose up -d
#

version: '2.1'

services:

  pravega:
    image: pravega/pravega:0.2.1
    ports:
      - "9090:9090"
      - "12345:12345"
    command: standalone
    environment:
      HOST_IP: ${PRAVEGA_HOST_IP:-pravega}

  gateway:
    image: claudiofahey/taxidemo_gateway
    build:
      context: gateway
    ports:
      - "3000:3000"
    environment:
      PRAVEGA_CONTROLLER: tcp://${PRAVEGA_HOST_IP:-pravega}:9090
      ROUTING_KEY_ATTRIBUTE_NAME: trip_id
    restart: on-failure

  streaming_data_generator:
    image: claudiofahey/taxidemo_streaming_data_generator
    build:
      context: streaming_data_generator
    command:
      - ./streaming_data_generator.py
      - --gateway-url
      - http://gateway:3000/data
      - --start-at-first-line
      - /data/*.json
    volumes:
      - ./notebooks/data.json:/data:ro
