#
# This Docker Compose file will create a complete system to run this demo.
#
# To build from source:
#   ./gradlew gateway:distTar && docker-compose build
#

version: '2.1'

services:

  gateway:
    image: claudiofahey/taxidemo_gateway
    build:
      context: gateway
    ports:
      - "3000:3000"
    environment:
      BRAIN_PRAVEGA_CONTROLLER: tcp://${PRAVEGA_HOST_IP:-pravega}:9090
    restart: on-failure

  streaming_data_generator:
    image: claudiofahey/taxidemo_streaming_data_generator
    build:
      context: streaming_data_generator
    command:
      - ./streaming_data_generator.py
      - -n
      - "4"     # Change this to "0" to disable the streaming data generator.
      - -r
      - -g
      - http://gateway:3000/data
