# https://github.com/elastic/elasticsearch-docker
FROM elasticsearch:5.5.2

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

COPY config /usr/share/elasticsearch/config
